nodes:
  type: list
  subtype: union
  name: Lightning Nodes
  description: List of Lightning Network node instances to manage
  range: "[1,*)"
  default:
  - lnd
  spec:
    displayAs: "{{name}}"
    uniqueBy: name
    name: Node Implementation
    tag:
      id: type
      name: Type
      description: |
        - LND: Lightning Network Daemon from Lightning Labs
        - C-Lightning: C-Lightning from Blockstream
      variantNames:
        lnd: LND
        c-lightning: C-Lightning
    default: lnd
    variants:
      lnd:
        name:
          type: string
          name: Node Name
          description: Name of this node in the list
          default: "Embassy LND"
          nullable: false
        connection-settings:
          type: union
          name: Connection Settings
          description: The Lightning Network Daemon node to connect to.
          tag:
            id: type
            name: Type
            description: |
              - Internal: The Lightning Network Daemon service installed to your Embassy.
              - External: A Lightning Network Daemon instance running on a remote device (advanced).
            variantNames:
              internal: Internal
              external: External
          default: internal
          variants:
            internal:
              address:
                type: pointer
                name: Local Address
                description: The LAN IP address of your Lightning Network Daemon service
                subtype: app
                app-id: lnd
                target: lan-address
            external:
              address:
                type: string
                name: Public Address
                description: |
                  The public address of your LND REST server
                  NOTE: RTL does not support a .onion URL here
                nullable: false
              rest-port:
                type: number
                name: REST Port
                description: The port that your Lightning Network Daemon REST server is bound to
                nullable: false
                range: "[0,65535]"
                integral: true
                default: 8080
              macaroon:
                type: string
                name: Macaroon
                description: Your admin.macaroon file, Base64URL encoded. This is the same as the value after "macaroon=" in your lndconnect URL.
                nullable: false
                masked: true
              cert:
                type: string
                name: TLS Cert
                description: Your tls.cert file, Base64URL encoded. This is the same as the value after "cert=" in your lndconnect URL.
                nullable: false
      c-lightning:
        name:
          type: string
          name: Node Name
          description: Name of this node in the list
          default: "Embassy C-Lightning"
          nullable: false
        connection-settings:
          type: union
          name: Connection Settings
          description: The C-Lightning node to connect to.
          tag:
            id: type
            name: Type
            description: |
              - Internal: The C-Lightning service installed to your Embassy.
              - External: A C-Lightning instance running on a remote device (advanced).
            variantNames:
              internal: Internal
              external: External
          default: internal
          variants:
            internal:
              address:
                type: pointer
                name: Local Address
                description: The LAN IP address of your C-Lightning service
                subtype: app
                app-id: c-lightning
                target: lan-address
            external:
              address:
                type: string
                name: Public Address
                description: |
                  The public address of your C-Lightning-REST server
                  NOTE: RTL does not support a .onion URL here
                nullable: false
              rest-port:
                type: number
                name: REST Port
                description: The port that your C-Lightning-REST server is bound to
                nullable: false
                range: "[0,65535]"
                integral: true
                default: 3001
              macaroon:
                type: string
                name: Macaroon
                description: Your C-Lightning-REST access.macaroon file, Base64URL encoded.
                nullable: false
                masked: true
              cert:
                type: string
                name: TLS Cert
                description: Your C-Lightning-REST certificate.pem file, Base64URL encoded.
                nullable: false
password:
  type: string
  name: Password
  description: The password for your Ride the Lightning dashboard
  nullable: false
  copyable: true
  masked: true
  default:
    charset: "a-z,A-Z,0-9"
    len: 22